spring:
  application:
    name: marketing-image-api-server

  config:
    import: "classpath:aws-credentials.yaml"

  datasource:
    url: jdbc:mariadb://localhost:3306/marketing-image?userSSL=false
    username: tod
    password: 1234
    driver-class-name: org.mariadb.jdbc.Driver
    hikari:
      connection-timeout: 20000
      minimum-idle: 10
      maximum-pool-size: 10
      idle-timeout: 300000
      pool-name: marketingHikariCP


cloud:
  aws:
    region:
      static: ap-northeast-2
    credentials:
      access-key: ${aws.credentials.s3.access-key}
      secret-key: ${aws.credentials.s3.secret-key}
debug: true

