spring:
  application:
    name: marketing-image-api-server
  profiles:
    group:
      local: db-local
      prod: db-prod
      aws: db-aws
  config:
    import:
      - "classpath:aws-credentials.yaml"
      - "classpath:application-db.yaml"


cloud:
  aws:
    region:
      static: ap-northeast-2
    credentials:
      access-key: ${aws.credentials.s3.access-key}
      secret-key: ${aws.credentials.s3.secret-key}
debug: true

